### ISSUE TITLE
代码请教

### ISSUE THREAD

**Issue by HuCutie** [localhostjason/dnf-console#2]
你好啊，我并不熟悉go语言，不知道该如何编译才能得到Linux下的可执行文件呢？ 希望能给出一些指导，谢谢！

**Comment by localhostjason** [comment]
linux 我这边举例 Redhat 例子
1. 安装 golang 
2. console 目录下， 执行 `go build main.go`
3. ./main -i
4. ./main -x （当然也可以 ./main -k start 或者 ./main -k stop）

**Comment by HuCutie** [comment]
好的感谢回复哈。这样子web也启动了吗？ 我不太懂前端，后端的go语言部分那天我摸索出来了，可以正常编译启动。而且我发现是不是不支持中文的角色名？ 我角色名是中文的，windows下启动控制台查询了一下之后再登游戏所有的角色名都变成了??????

**Comment by localhostjason** [comment]
https://github.com/localhostjason/dnf-console/commit/b9ad59a1357b112980b9a3d942f2b9139549d467
已经修复了

**Comment by localhostjason** [comment]
![image](https://github.com/localhostjason/dnf-console/assets/17875243/b5475f98-eb72-451a-bafe-b3051433f3bc)

**Comment by HuCutie** [comment]
嗯，现在部署和简单的修改我已经掌握了，感谢作者的源码。在邮件管理界面进行物品搜索时，物品信息是存放在哪里的？ 我看源码下有gold.txt，我修改之后重新编译运行也没有变化，请问如果需要添加物品信息应该怎么做呢？

**Comment by HuCutie** [comment]
Hello?  请问有人会改这个需求嘛，邮件管理中加载的信息

**Comment by RShifts** [comment]
> Hello? 请问有人会改这个需求嘛，邮件管理中加载的信息

 你在执行目录下的source/gold.txt 里按格式加上就可以了 （记得重新 ./main -i 一下）
